name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk

    - name: Build the project
      run: mvn package
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: hyperpeam1/trandoan92ag:latest

    - name: SSH to EC2 instance and start the application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          kubectl apply -f petstore.yaml

#     - name: Copy jar file to EC2 instance
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.REMOTE_HOST }}
#         username: ${{ secrets.REMOTE_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         source: "target/openapi-petstore-*.jar"
#         target: "/home/ec2-user/app.jar"

#     - name: SSH to EC2 instance and stop the application
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.REMOTE_HOST }}
#         username: ${{ secrets.REMOTE_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           pkill -f app.jar

#     - name: SSH to EC2 instance and start the application
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.REMOTE_HOST }}
#         username: ${{ secrets.REMOTE_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           nohup java -jar /home/ec2-user/app.jar > app.log 2>&1 &
# #          sudo systemctl start app.jar
